// src/AppControls.vue
<template>
  <div>
    {{ zeroPadCountdown }}
    <button type="button" class="btn hover:bg-gray-100" @click="toggle">
      <i class="fas fa-play" v-if="paused"></i>
      <i class="fas fa-pause" v-else></i>
    </button>
    <button type="button" class="btn hover:bg-gray-100" @click="refresh">
      <i class="fas fa-sync-alt" :class="{ 'fa-pulse': loading }"></i>
    </button>
  </div>
</template>

<script>
import { mapGetters } from "vuex";

export default {
  computed: {
    zeroPadCountdown() {
      return `${this.$store.state.countdown}`.padStart(2, "0");
    },
    ...mapGetters({
      loading: "anyLoading",
      paused: "paused",
    }),
  },
  methods: {
    refresh() {
      this.$store.dispatch("refresh");
    },
    toggle() {
      this.$store.dispatch(this.paused ? "resume" : "pause");
    },
  },
};
</script>

// frontend/AppControls.svelte
<script>
  import _ from "lodash";
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();
  export let countdown, paused, loading;

  $: zeroPadCountdown = _.padStart(`${countdown}`, 2, "0");

  function refresh() {
    dispatch("refresh");
  }

  function toggle() {
    if (paused) dispatch("resume");
    else dispatch("pause");
  }
</script>

<div>
  {zeroPadCountdown}
  <button
    type="button"
    class="ph3 pv2 ba b--light-gray bg-transparent hover-bg-light-gray"
    on:click="{toggle}"
  >
    {#if paused}
    <i class="fas fa-play"></i>
    {:else}
    <i class="fas fa-pause"></i>
    {/if}
  </button>
  <button
    type="button"
    class="ph3 pv2 ba b--light-gray bg-transparent hover-bg-light-gray"
    on:click="{refresh}"
  >
    <i class="fas fa-sync-alt" class:fa-pulse="{loading}"></i>
  </button>
</div>
