// src/App.vue
<template>
  <div class="w-full avenir">
    <div class="flex flex-wrap justify-between items-center p-2 border shadow">
      <h3 class="my-0">{{ title }}</h3>
      <div class="text-right">
        <AppControls></AppControls>
      </div>
    </div>
    <div class="flex flex-wrap">
      <div
        class="w-full p-3 md:w-1/2 lg:w-1/3 xl:w-1/4"
        v-for="site in sites"
        :key="site.url"
      >
        <StatusTile
          :name="site.name"
          :url="site.url"
          :status="site.status"
          :elapsed="site.elapsed"
        ></StatusTile>
      </div>
    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";
import StatusTile from "./StatusTile.vue";
import AppControls from "./AppControls.vue";

export default {
  mounted() {
    document.title = this.$store.state.title;
    this.$store.dispatch("resume");
    this.$store.dispatch("refresh");
  },
  computed: mapState({
    title: "title",
    sites: "sites",
  }),
  components: { StatusTile, AppControls },
};
</script>

// frontend-react/src/App.jsx
import React from "react";
import AppControls from "./AppControls";
import StatusTile from "./StatusTile";
import { connect } from "react-redux";
import { startInterval, refresh } from "./redux/actions";

class App extends React.Component {
  componentDidMount() {
    document.title = this.props.title;
    this.props.onStartInterval();
    this.props.onRefresh();
  }

  render() {
    return (
      <div className="w-100 avenir">
        <div className="flex flex-wrap justify-between items-center pa2 bb b--light-gray">
          <h3 className="mv0">{this.props.title}</h3>
          <div className="tr">
            <AppControls />
          </div>
        </div>
        <div className="flex flex-wrap">
          {this.props.sites.map(site => (
            <div className="w-100 w-50-m w-25-l pa2" key={site.url}>
              <StatusTile
                name={site.name}
                url={site.url}
                status={site.status}
                elapsed={site.elapsed}
              />
            </div>
          ))}
        </div>
      </div>
    );
  }
}

function mapStateToProps(state) {
  return {
    sites: state.sites,
    title: state.title
  };
}

function mapDispatchToProps(dispatch) {
  return {
    onRefresh: () => dispatch(refresh()),
    onStartInterval: () => dispatch(startInterval())
  };
}

export default connect(mapStateToProps, mapDispatchToProps)(App);
